server:
  port: 8762

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_db?serverTimezone=UTC
    username: root
    password: Yuesi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
